title: Swift Code Show
email: swiftcodeshow@gmail.com
description: "Topics, Codes and Key Points"
baseurl: ""
url: "https://swiftcodeshow.com"

google_analytics: G-L7HJNDNMCD

# Build settings
plugins:
   - jekyll-feed

theme: jekyll-theme-cayman
